name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # каждые 5 часов

jobs:
  run-bot:
    runs-on: ubuntu-latest

    concurrency:
      group: bot-restart
      cancel-in-progress: false

    env:
      TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Setup Actions
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Fetch Token
        run: |
          sed -i "s/^token:.*/token: \"${TOKEN}\"/" config.yml
          
      - name: Make Stockfish executable
        run: chmod +x ./engines/stockfish.exe

      - name: Run Bot
        run:  python user_interface.py 
